<?php
$_product = $this->getProduct();
$_attributes = Mage::helper('core')->decorateArray($this->getAllowAttributes());
$swatch_attributes = Mage::helper('colorselectorplus')->getSwatchAttributes();
$title = Mage::getStoreConfig('color_selector_plus/colorselectorplusgeneral/title', Mage::app()->getStore());
$hide = Mage::getStoreConfig('color_selector_plus/colorselectorplusgeneral/hidedropdown', Mage::app()->getStore());
?>

<?php if ($_product->isSaleable() && count($_attributes)): ?>
    <dl>
    	<?php foreach($_attributes as $_attribute): ?>
			<?php $_productAttribute = $_attribute->getProductAttribute(); ?>
			<?php 
      $storeId   = Mage::app()->getStore()->getId();
      $_attributeCode = $_productAttribute->getAttributeCode();
      $_label = $_productAttribute->getFrontendLabel();
      if($_attributeCode == 'color') {
          $_label = '';
          $title = '';
      }
      else {
        if($hide==1) {
          $title = ' - <span id="divattribute'. $attributeId.'" class="swatchLabel">'.$title.'</span>';
        }
        else {
          $title = '';
        }
      }
      ?>
			<?php if(in_array($_attributeCode, $swatch_attributes)): ?>
				<?php $attributeId = $_attribute->getAttributeId(); ?>
       			<dd<?php if ($_attribute->decoratedIsLast){?> class="last <?php echo $_attributeCode; ?>"<?php }?>>
              <label class="required"><?php echo $_label ?></label>
            	<div class="input-box">
              	<select name="super_attribute[<?php echo $attributeId ?>]" id="attribute<?php echo $attributeId ?>" class="required-entry super-attribute-select<?php if($hide == 1) echo ' swatchSelect' ?>">
               		<option><?php echo $this->__('Choose an Option...') ?></option>
             		</select>
           		</div>
					    <?php echo Mage::helper('colorselectorplus')->getSwatchHtml($_attributeCode, $attributeId, $_product); ?>
              <div style="display: none;" id="advice-required-entry-attribute<?php echo $attributeId ?>" class="validation-advice"><?php echo $this->__('This is a required field.') ?></div>
          	</dd>
     		<?php else: ?>
        		<dd<?php if ($_attribute->decoratedIsLast){?> class="last <?php echo $_attributeCode; ?>"<?php }?>>
              <label class="required"><?php echo $_label ?></label>
            		<div class="input-box">
                		<select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute-select">
                    		<option><?php echo $this->__('Choose an Option...') ?></option>
                  		</select>
              		</div>
                  <?php if($_attributeCode=='size'): ?>
                    <a href="#" class="link link-size-chart">
                      <span><?php echo $this->__('Size chart'); ?></span>
                    </a>
                    <div style="display: none;">
                      <div class="size-chart-popup-wrapper">
                        <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('size_chart')->toHtml(); ?>
                      </div>
                    </div>
                    <script type="text/javascript">
                    jQuery(document).ready(function($) {
                      $('.link-size-chart').colorbox({
                        inline:true,
                        href: $('.size-chart-popup-wrapper'),
                        className: 'colorbox-size-chart'
                      })
                    });
                    </script>
                  <?php endif; ?>
                </dd>
   			<?php endif; ?>
    	
    	<?php endforeach; ?>
	<script type="text/javascript">
		var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
		var selecttitle = '<?php echo $title ?>';
    </script>
<?php endif;
