<?php $helper = Mage::helper('customweb_subscription') ?>
<?php $subscription = $this->getSubscription() ?>
<div class="grid np">
  <div class="hor-scroll">
    <table cellspacing="0" class="data order-tables">
        <col />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <col width="1" />
        <thead>
            <tr class="headings">
                <th><?php echo $helper->__('Product') ?></th>
                <th><?php echo $helper->__('Price') ?></th>
                <th class="a-center"><?php echo $helper->__('Qty') ?></th>
                <th><?php echo $helper->__('Subtotal') ?></th>
                <th><span class="nobr"><?php echo $helper->__('Tax Amount') ?></span></th>
                <th><span class="nobr"><?php echo $helper->__('Discount Amount') ?></span></th>
                <th><span class="nobr"><?php echo $helper->__('Row Total') ?></span></th>
                <th class="last"><span class="nobr"><?php echo $helper->__('In Stock') ?></span></th>
            </tr>
        </thead>
        <?php $items = $subscription->getItems() ?>
        <?php $i=0; foreach ($items as $item):?>
            <?php if ($item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($item) ?>
                <?php echo $this->getItemExtraInfoHtml($item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
  </div>
</div>
<br />